export type QuizTestCase = {
  id: string;
  label: string;
  sourcePlace: string;
  likes: string;
  usefulPlacesNearby: string;
  citySlug: "nyc" | "toronto" | "mumbai";
  budgetMin: number;
  budgetMax: number;
  lifestylePicks: string[];
  nearbyPriorities: string[];
  mobilityPreference: string;
  tradeoffs: string[];
};

export const DEFAULT_TEST_CASE_ID = "dense-transit-nightlife";

export const QUIZ_TEST_CASES: QuizTestCase[] = [
  {
    id: "dense-transit-nightlife",
    label: "Logan Square, Chicago -> NYC",
    sourcePlace: "Logan Square, Chicago",
    likes: "I liked being near bars, music venues, late-night food, and independent coffee shops. I did not need everything to be polished, but I wanted the area to feel active after work and easy to explore without driving.",
    usefulPlacesNearby: "Coffee, casual dinner, groceries, train access, and a few places to meet friends within a short walk.",
    citySlug: "nyc",
    budgetMin: 2800,
    budgetMax: 3700,
    lifestylePicks: ["Good coffee", "Nightlife", "Public transit", "Social energy", "Great food"],
    nearbyPriorities: ["Coffee shops", "Restaurants", "Grocery shops", "Public transport", "Nightlife"],
    mobilityPreference: "Public transport",
    tradeoffs: ["Transit access over driving", "Social energy over calm", "Better location over more space"],
  },
  {
    id: "quiet-family-practical",
    label: "Decatur, Georgia -> Toronto",
    sourcePlace: "Decatur, Georgia",
    likes: "I liked the calmer residential feel, older houses, tree-lined streets, good schools, parks, and a small downtown with useful errands. I want neighborhood life without feeling isolated.",
    usefulPlacesNearby: "Parks, grocery stores, pharmacy, pediatric care, library, and low-stress restaurants.",
    citySlug: "toronto",
    budgetMin: 2500,
    budgetMax: 3300,
    lifestylePicks: ["Quiet streets", "Parks nearby", "Safer-feeling area", "Walkable errands"],
    nearbyPriorities: ["Parks", "Grocery shops", "Pharmacies", "Restaurants"],
    mobilityPreference: "Mostly walking",
    tradeoffs: ["Quiet over nightlife", "Familiar vibe over adventure"],
  },
  {
    id: "high-energy-urban-core",
    label: "Capitol Hill, Seattle -> NYC",
    sourcePlace: "Capitol Hill, Seattle",
    likes: "I liked being in the middle of everything: restaurants, queer nightlife, bookstores, dense apartments, and transit. I am okay with some noise if it means I rarely need a car.",
    usefulPlacesNearby: "Transit, late-night food, fitness studios, bars, coffee shops, and everyday groceries.",
    citySlug: "nyc",
    budgetMin: 3000,
    budgetMax: 4200,
    lifestylePicks: ["Nightlife", "Public transit", "Social energy", "Creative scene", "Great food"],
    nearbyPriorities: ["Public transport", "Restaurants", "Gyms", "Nightlife", "Coffee shops", "Grocery shops"],
    mobilityPreference: "Public transport",
    tradeoffs: ["Social energy over calm", "Transit access over driving", "Better location over more space"],
  },
  {
    id: "walkable-not-too-loud",
    label: "Park Slope, Brooklyn -> Toronto",
    sourcePlace: "Park Slope, Brooklyn",
    likes: "I liked having parks, brownstone streets, good cafes, bookstores, families, and restaurants nearby. I want walkability and character, but I do not want constant nightlife outside my window.",
    usefulPlacesNearby: "Large park, grocery, coffee, casual restaurants, good subway access, and weekend errands.",
    citySlug: "toronto",
    budgetMin: 2700,
    budgetMax: 3600,
    lifestylePicks: ["Parks nearby", "Good coffee", "Walkable errands", "Quiet streets", "Great food"],
    nearbyPriorities: ["Parks", "Grocery shops", "Coffee shops", "Restaurants", "Public transport"],
    mobilityPreference: "Mostly walking",
    tradeoffs: ["Quiet over nightlife", "Better location over more space"],
  },
  {
    id: "suburban-comfort-city-access",
    label: "Arlington, Virginia -> NYC",
    sourcePlace: "Arlington, Virginia",
    likes: "I liked that it felt clean, practical, and safe, with reliable transit into the city. I want newer apartments, gyms, grocery stores, and restaurants nearby, but I do not need a super edgy neighborhood.",
    usefulPlacesNearby: "Metro or train access, grocery, gym, pharmacy, casual food, and a clean public realm.",
    citySlug: "nyc",
    budgetMin: 3200,
    budgetMax: 4500,
    lifestylePicks: ["Safer-feeling area", "Public transit", "Groceries close", "Walkable errands"],
    nearbyPriorities: ["Public transport", "Grocery shops", "Gyms", "Pharmacies", "Restaurants"],
    mobilityPreference: "Public transport",
    tradeoffs: ["Transit access over driving", "Familiar vibe over adventure"],
  },
  {
    id: "creative-student-budget",
    label: "Dinkytown, Minneapolis -> Toronto",
    sourcePlace: "Dinkytown, Minneapolis",
    likes: "I liked the student energy, cheap food, bikeability, cafes to study in, and casual bars. I want an affordable area where there are always people around and I can get by without a car.",
    usefulPlacesNearby: "Cheap eats, coffee shops, transit, bike routes, grocery, and casual nightlife.",
    citySlug: "toronto",
    budgetMin: 1900,
    budgetMax: 2600,
    lifestylePicks: ["Budget-friendly", "Good coffee", "Public transit", "Social energy", "Nightlife"],
    nearbyPriorities: ["Restaurants", "Coffee shops", "Public transport", "Grocery shops", "Nightlife"],
    mobilityPreference: "Bike friendly",
    tradeoffs: ["Cheaper rent over perfect location", "Transit access over driving", "Social energy over calm"],
  },
  {
    id: "coastal-wellness-calm",
    label: "Santa Monica, California -> Mumbai",
    sourcePlace: "Santa Monica, California",
    likes: "I liked being close to the beach, parks, fitness classes, healthy food, and outdoor space. I care more about wellness, light, and safety than nightlife.",
    usefulPlacesNearby: "Parks, waterfront or trails, yoga or fitness, healthy restaurants, grocery, and quiet cafes.",
    citySlug: "mumbai",
    budgetMin: 90000,
    budgetMax: 160000,
    lifestylePicks: ["Parks nearby", "Safer-feeling area", "Quiet streets", "Great food"],
    nearbyPriorities: ["Parks", "Gyms", "Restaurants", "Grocery shops", "Coffee shops"],
    mobilityPreference: "Mostly walking",
    tradeoffs: ["Quiet over nightlife", "Better location over more space"],
  },
  {
    id: "market-streets-food-culture",
    label: "Bandra West, Mumbai -> NYC",
    sourcePlace: "Bandra West, Mumbai",
    likes: "I liked the street life, cafes, restaurants, shopping, old buildings, and the feeling that something interesting was always close by. I can handle traffic and density if the neighborhood has personality.",
    usefulPlacesNearby: "Restaurants, cafes, markets, nightlife, grocery, and places to walk with friends.",
    citySlug: "nyc",
    budgetMin: 3000,
    budgetMax: 4300,
    lifestylePicks: ["Good coffee", "Nightlife", "Walkable errands", "Social energy", "Great food"],
    nearbyPriorities: ["Restaurants", "Coffee shops", "Nightlife", "Grocery shops"],
    mobilityPreference: "Mostly walking",
    tradeoffs: ["Social energy over calm", "New adventure over familiar vibe"],
  },
  {
    id: "tech-worker-commute",
    label: "Koramangala, Bangalore -> Toronto",
    sourcePlace: "Koramangala, Bangalore",
    likes: "I liked being around startups, coworking spaces, cafes, gyms, and restaurants. I want a practical base with professional energy, good food, and a manageable commute.",
    usefulPlacesNearby: "Coworking, cafes, gym, restaurants, pharmacy, groceries, and transit or commute options.",
    citySlug: "toronto",
    budgetMin: 2300,
    budgetMax: 3200,
    lifestylePicks: ["Good coffee", "Public transit", "Groceries close", "Social energy", "Great food"],
    nearbyPriorities: ["Coworking", "Coffee shops", "Gyms", "Restaurants", "Pharmacies", "Grocery shops", "Public transport"],
    mobilityPreference: "Public transport",
    tradeoffs: ["Transit access over driving", "Better location over more space"],
  },
  {
    id: "historic-artsy-tourist",
    label: "French Quarter, New Orleans -> NYC",
    sourcePlace: "French Quarter, New Orleans",
    likes: "I loved the historic buildings, live music, restaurants, walkability, and sense of place. I do not mind tourists or noise as long as the neighborhood feels distinctive and alive.",
    usefulPlacesNearby: "Music venues, restaurants, bars, coffee, groceries, and streets that are fun to walk.",
    citySlug: "nyc",
    budgetMin: 2900,
    budgetMax: 4000,
    lifestylePicks: ["Nightlife", "Creative scene", "Walkable errands", "Social energy", "Great food"],
    nearbyPriorities: ["Nightlife", "Restaurants", "Coffee shops", "Grocery shops"],
    mobilityPreference: "Mostly walking",
    tradeoffs: ["Social energy over calm", "New adventure over familiar vibe"],
  },
  {
    id: "ambiguous-source-place",
    label: "Springfield -> Toronto",
    sourcePlace: "Springfield",
    likes: "I liked that it was affordable, easy to drive around, and had quiet streets, but I still wanted a few cafes, groceries, and parks nearby. I do not want an expensive nightlife district.",
    usefulPlacesNearby: "Grocery, parks, pharmacy, casual restaurants, parking, and simple errands.",
    citySlug: "toronto",
    budgetMin: 1800,
    budgetMax: 2500,
    lifestylePicks: ["Budget-friendly", "Quiet streets", "Parks nearby", "Groceries close"],
    nearbyPriorities: ["Grocery shops", "Parks", "Pharmacies", "Restaurants"],
    mobilityPreference: "Driving",
    tradeoffs: ["Cheaper rent over perfect location", "Quiet over nightlife"],
  },
  {
    id: "sparse-source-rich-preferences",
    label: "Near downtown -> Mumbai",
    sourcePlace: "Near downtown",
    likes: "I liked being able to walk to work, grab dinner without planning, and feel connected to the city. I want convenience, transit, and good everyday places more than a quiet residential feel.",
    usefulPlacesNearby: "Transit, lunch spots, grocery, pharmacy, coffee, gym, and casual dinner.",
    citySlug: "mumbai",
    budgetMin: 75000,
    budgetMax: 130000,
    lifestylePicks: ["Public transit", "Walkable errands", "Social energy", "Great food", "Good coffee"],
    nearbyPriorities: ["Public transport", "Restaurants", "Grocery shops", "Pharmacies", "Coffee shops", "Gyms"],
    mobilityPreference: "Mostly walking",
    tradeoffs: ["Better location over more space", "Transit access over driving"],
  },
  {
    id: "luxury-clean-amenity",
    label: "Brickell, Miami -> NYC",
    sourcePlace: "Brickell, Miami",
    likes: "I liked the newer high-rises, water views, gyms, restaurants, bars, and polished feeling. I want convenience, safety, and a lively professional crowd.",
    usefulPlacesNearby: "Gym, upscale grocery, restaurants, bars, waterfront walking, pharmacy, and transit.",
    citySlug: "nyc",
    budgetMin: 4000,
    budgetMax: 6000,
    lifestylePicks: ["Safer-feeling area", "Nightlife", "Social energy", "Great food", "Walkable errands"],
    nearbyPriorities: ["Gyms", "Grocery shops", "Restaurants", "Nightlife", "Pharmacies", "Public transport"],
    mobilityPreference: "Mostly walking",
    tradeoffs: ["Better location over more space", "Social energy over calm"],
  },
  {
    id: "nature-first-lower-density",
    label: "Boulder, Colorado -> Toronto",
    sourcePlace: "Boulder, Colorado",
    likes: "I liked mountain access, trails, bike paths, farmers markets, breweries, and a health-focused culture. I prefer calm streets and outdoor life over dense nightlife.",
    usefulPlacesNearby: "Parks, trails, bike routes, grocery, cafes, fitness, and casual restaurants.",
    citySlug: "toronto",
    budgetMin: 2400,
    budgetMax: 3200,
    lifestylePicks: ["Parks nearby", "Quiet streets", "Good coffee", "Groceries close"],
    nearbyPriorities: ["Parks", "Grocery shops", "Coffee shops", "Gyms", "Restaurants"],
    mobilityPreference: "Bike friendly",
    tradeoffs: ["Quiet over nightlife", "New adventure over familiar vibe"],
  },
  {
    id: "strong-dislike-signal",
    label: "Midtown Manhattan -> NYC",
    sourcePlace: "Midtown Manhattan",
    likes: "I liked the subway access and endless food options, but I hated the crowds, tourist traffic, sirens, and feeling like every block was stressful. I want convenience without that level of intensity.",
    usefulPlacesNearby: "Subway, groceries, restaurants, pharmacy, quiet cafes, and parks.",
    citySlug: "nyc",
    budgetMin: 3200,
    budgetMax: 4300,
    lifestylePicks: ["Public transit", "Great food", "Quiet streets", "Parks nearby", "Good coffee"],
    nearbyPriorities: ["Public transport", "Grocery shops", "Restaurants", "Pharmacies", "Coffee shops", "Parks"],
    mobilityPreference: "Public transport",
    tradeoffs: ["Quiet over nightlife", "Better location over more space"],
  },
];

export function getQuizTestCase(id: string) {
  return QUIZ_TEST_CASES.find((testCase) => testCase.id === id) || QUIZ_TEST_CASES[0];
}
